apiVersion: v1

kind: Service
metadata:
  name: spring-svc
spec:
  ports:
    - name: server-port
      port: 8080
      targetPort: 8080
      nodePort: 30100
  selector:
    app: spring-server
  type: NodePort
